# docker-composeのバージョンを指定
version: "3.9"

# db(MySQL),app(Flask)のコンテナを作成
services:
  app:
    # コンテナ名をFlaskに設定
    container_name: Flask
    # FlaskのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: Docker/Flask/Dockerfile
    # ボリュームを指定
    # ローカルのカレントディレクトリをコンテナの/codeにマウントする
    volumes:
      - ./ChatApp:/code
    # ローカルの5000番ポートとコンテナの5000番ポートをつなぐ
    ports:
      - "5000:5000"
    # コマンドを実行
    command:  bash -c "python app.py"

volumes:
  mysql_data:
