DROP DATABASE designgreat;
DROP USER 'testuser';

CREATE USER 'testuser' IDENTIFIED BY 'testuser';
CREATE DATABASE designgreat;
USE designgreat
GRANT ALL PRIVILEGES ON designgreat.* TO 'testuser';

CREATE TABLE roles (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  role_name varchar(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  user_name varchar(255) UNIQUE NOT NULL,
  password varchar(100) NOT NULL,
  teacher_password varchar(100),
  email varchar(255) NOT NULL UNIQUE,
  role_id int UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE channels (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  channel_name varchar(255) UNIQUE NOt NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE messages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  user_id int UNSIGNED NOT NULL,
  channels_id int UNSIGNED NOT NULL,
  message int UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (channels_id) REFERENCES channels(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pin_messages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  message_id int UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE user_reactions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  message_id int UNSIGNED NOT NULL,
  reaction_id int UNSIGNED NOT NULL,
  user_id int UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE icons (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  icon_name varchar(255) NOT NULL,
  image_path varchar(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE reactions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  reaction_name varchar(255) NOT NULL,
  icon_id int UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (icon_id) REFERENCES icons(id) ON DELETE CASCADE ON UPDATE CASCADE
);
